Restructure market
plotx/smart-contracts pull request #120
Opened 2020-11-17 06:32 UTC by nitika-goel

- Converting multiple market contracts to a single market contract

- Removing Leverage Functionality 

- Implementing Deposit & Predict

- Circling Back Rewards 

- Option pricing, changing to relative positions instead of participation amount per transaction

2020-12-04 06:17 UTC, maxsam4 requested changes

2020-12-04 06:17 UTC, maxsam4 commented on contracts/MarketCreationRewards.sol
> +      address createdBy;
converting `uint64` to `uint16` will allow it to be packed with `address`, saving one storage operation.

2020-12-04 06:17 UTC, maxsam4 commented on contracts/MarketCreationRewards.sol
> +      uint256[] marketsCreated;
`_marketId` is `u64` so this can be made a `u64` array instead `u256` array.

Also consider converting `_marketId` to `u32` since `u64` seems a bit overkill.

2020-12-04 06:17 UTC, maxsam4 commented on contracts/MarketCreationRewards.sol
> +    uint64 internal minRewardPoolPercForMC;
indentation

2020-12-04 06:17 UTC, maxsam4 commented on contracts/MarketCreationRewards.sol
> +    uint256 internal maxGasPrice;
All % can be converted to `u16` for more efficient packing.

2020-12-04 06:17 UTC, maxsam4 commented on contracts/MarketCreationRewards.sol
> +      gasUsed = gasProvided - gasleft();
```suggestion
      //Adding buffer gas for below calculations
      gasUsed = gasProvided - gasleft() + 38500;
```

2020-12-04 06:17 UTC, maxsam4 commented on contracts/MarketCreationRewards.sol
> +      gasUsed = 38500;
Does this buffer account for the 21k gas needed to initiate the transaction?

2020-12-04 06:17 UTC, maxsam4 commented on contracts/MarketCreationRewards.sol
> +		  _transferAsset(plotToken, msg.sender, marketCreationRewardData[_marketId].plotIncentive);
Indentation

2020-12-04 06:17 UTC, maxsam4 commented on contracts/AllMarkets.sol
> +    function burnDisputedProposalTokens(uint _proposalId) external {
Without any access control, anyone can call this and burn disputed proposal tokens.

2020-12-04 06:58 UTC, udkreddySomish commented on contracts/AllMarkets.sol
> +    function burnDisputedProposalTokens(uint _proposalId) external {
Added modifier, only authorized to governance

2020-12-04 07:00 UTC, udkreddySomish commented on contracts/MarketCreationRewards.sol
> +		  _transferAsset(plotToken, msg.sender, marketCreationRewardData[_marketId].plotIncentive);
Corrected

2020-12-04 07:48 UTC, udkreddySomish commented on contracts/MarketCreationRewards.sol
> +    uint64 internal minRewardPoolPercForMC;
corrected

2020-12-04 10:02 UTC, udkreddySomish commented on contracts/MarketCreationRewards.sol
> +      address createdBy;
Updated to uint16

2020-12-04 10:12 UTC, udkreddySomish commented on contracts/MarketCreationRewards.sol
> +      gasUsed = gasProvided - gasleft();
Fixed

2020-12-04 11:19 UTC, udkreddySomish commented on contracts/MarketCreationRewards.sol
> +      gasUsed = 38500;
Yes, but the value was outdated.
Had updated the buffer value with the latest gas difference

2020-12-04 11:32 UTC, udkreddySomish commented on contracts/GovernanceNew.sol
> +contract GovernanceNew is Governance {
Yes, renamed all new contracts with version

2020-12-04 11:38 UTC, udkreddySomish commented on contracts/MarketCreationRewards.sol
> +    uint256 internal maxGasPrice;
Updated

2020-12-07 04:02 UTC, udkreddySomish commented on contracts/MarketCreationRewards.sol
> +      uint256[] marketsCreated;
Corrected

2020-12-07 06:40 UTC, maxsam4 commented on contracts/AllMarkets.sol
> +      _storePredictionData(_marketId, _prediction, _commissionStake, _asset, predictionPoints);
The third parameter in this function is supposed to be `_predictionStake`

2020-12-07 06:40 UTC, maxsam4 commented on contracts/AllMarkets.sol
> +    function placePrediction(uint _marketId, address _asset, uint64 _predictionStake, uint256 _prediction) public {
I am not a fan of taking `_predictionStake` as input without the decimals and then multiplying it with the `predictionDecimalMultiplier` decimals. If you are going to do it, at least add code comments for it.

2020-12-07 07:02 UTC, udkreddySomish commented on contracts/AllMarkets.sol
> +      _storePredictionData(_marketId, _prediction, _commissionStake, _asset, predictionPoints);
No, we were actually storing the prediction stake value after deducting the commission
And that value is stored in _commissionStake variable in line : 495.
My mistake, will add proper comments in the code

2020-12-07 07:11 UTC, udkreddySomish commented on contracts/AllMarkets.sol
> +    function placePrediction(uint _marketId, address _asset, uint64 _predictionStake, uint256 _prediction) public {
Added comments in the file.
We were maintaining 8 decimals for `_predictionStake` to reduce the prediction data storage size.
and decimals for user deposit balance(`currencyUnusedBalance`) is maintained with regular 18decimals.
So `_predictionStake` is multiplied in order to maintain decimals with `currencyUnusedBalance`

2020-12-07 12:27 UTC, maxsam4 requested changes

2020-12-07 12:27 UTC, maxsam4 commented on contracts/AllMarkets.sol
> +      IToken(plotToken).transferFrom(msg.sender, address(this), _value);
Shouldn't you be transferring the `_token` token?

2020-12-07 12:27 UTC, maxsam4 commented on contracts/AllMarkets.sol
> +        require(msg.value == _ethDeposit);
There's no need to take `_ethDeposit` as input.

2020-12-07 12:27 UTC, maxsam4 commented on contracts/AllMarkets.sol
> +    }
This can be called infinite times to claim the incentive multiple times.

2020-12-07 12:27 UTC, maxsam4 commented on contracts/AllMarkets.sol
> +      delete marketDataExtended[_marketId].tokenAmountToPool;
`ethAmountToPool` and `tokenAmountToPool`  seem to be useless now

2020-12-07 12:27 UTC, maxsam4 commented on contracts/AllMarkets.sol
> +    * @dev Patayble Fallback function to recieve funds
```suggestion
    * @dev Payable fallback function to receive funds
```

2020-12-07 12:52 UTC, udkreddySomish commented on contracts/AllMarkets.sol
> +      IToken(plotToken).transferFrom(msg.sender, address(this), _value);
Fixed

2020-12-07 12:52 UTC, udkreddySomish commented on contracts/AllMarkets.sol
> +        require(msg.value == _ethDeposit);
Yes, removed

2020-12-07 12:58 UTC, udkreddySomish commented on contracts/AllMarkets.sol
> +      userData[msg.sender].currencyUnusedBalance[ETH_ADDRESS] = userData[msg.sender].currencyUnusedBalance[ETH_ADDRESS].add(msg.value);
Fixed

2020-12-07 13:30 UTC, udkreddySomish commented on contracts/AllMarkets.sol
> +      delete marketDataExtended[_marketId].tokenAmountToPool;
Yes, removed both.

2020-12-07 13:31 UTC, udkreddySomish commented on contracts/AllMarkets.sol
> +    * @dev Patayble Fallback function to recieve funds
Corrected

2020-12-07 18:44 UTC, udkreddySomish commented on contracts/AllMarkets.sol
> +    }
Fixed, and restructured the claimIncentive function, allowing user to claim for multiple markets

2020-12-07 18:47 UTC, udkreddySomish commented on contracts/AllMarkets.sol
> +      _ethLeft = _ethLeft.add(_ethReward);
Both of the variables are with 18 decimals, keeping it as precautionary.

2020-12-07 18:47 UTC, udkreddySomish commented on contracts/AllMarkets.sol
> +      _ethLeft = _ethLeft.add(_ethReward);
Both of the variables are with 18 decimals, keeping it as precautionary.

2020-12-08 06:58 UTC, maxsam4 commented on contracts/AllMarkets.sol
> +      _ethLeft = _ethLeft.add(_ethReward);
If this overflows, something else has gone horribly wrong. The sum of plotleft and plotreward must always be less than the total supply of plot and the total supply should always fit in u256. Anyway, it doesn't really matter.

2020-12-08 07:50 UTC, udkreddySomish commented on contracts/AllMarkets.sol
> +      _transferAsset(plotToken, msg.sender, _plot);
Updated

2020-12-08 17:32 UTC, maxsam4 approved these changes
I'd recommend fixing this last thing as well

2020-12-08 17:32 UTC, maxsam4 commented on contracts/AllMarkets.sol
> +        if(incentive > 0 && incentiveToken == _incentiveToken && !userData[_user].userMarketData[_markets[i]].incentiveClaimed) {
If the `incentiveToken` is different for any market from other markets, users will not be able to claim any incentives.

2020-12-09 07:22 UTC, udkreddySomish commented on contracts/AllMarkets.sol
> +        if(incentive > 0 && incentiveToken == _incentiveToken && !userData[_user].userMarketData[_markets[i]].incentiveClaimed) {
Yes, that was the intended behaviour
If user wants to claim for other markets, user should pass incentive token of that market

2020-12-14 17:12 UTC, merged